sodu: required 
services:
  - docker

before_install:
  - docker build -t shavendra/docker-react -f dockerfile.dev .
script:
  - docker run -e CI=true shavendra/docker-react npm run test
language: generic
